sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run deploy:dev
  - npm run deploy:prod
  - npm run deploy:prod-ssr

after_success:
  - npm run codecov
